// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Resto.API.Data;

#nullable disable

namespace Resto.API.Migrations
{
    [DbContext(typeof(RestoDbContext))]
    [Migration("20230915003048_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Resto.API.Model.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6e1305b1-56ae-4e2b-8ed0-6783983b0901"),
                            Name = "Shaka"
                        });
                });

            modelBuilder.Entity("Resto.API.Model.Domain.Food", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FoodDescription")
                        .IsRequired()
                        .HasColumnType("VARCHAR(250)");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<decimal>("FoodPrice")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1acf2f6-2a21-427c-a1ee-d3442664004b"),
                            FoodDescription = "Main Men",
                            FoodName = "Butter Garlic Sauce",
                            FoodPrice = 298000m
                        },
                        new
                        {
                            Id = new Guid("ed45ffaf-f684-4e5b-9508-d6fc930d44fc"),
                            FoodDescription = "Main Menu",
                            FoodName = "Singapore Chilli Sauce",
                            FoodPrice = 235000m
                        },
                        new
                        {
                            Id = new Guid("b542e7c7-8558-41e4-b516-e87cd420102c"),
                            FoodDescription = "Main Menu",
                            FoodName = "Bakar Bumbu Asap",
                            FoodPrice = 298000m
                        },
                        new
                        {
                            Id = new Guid("eb920cd4-dfe1-4c75-a3f8-fc6bf86a2b02"),
                            FoodDescription = "Vegetable",
                            FoodName = "Tumis Tauge Kecap",
                            FoodPrice = 235000m
                        },
                        new
                        {
                            Id = new Guid("cc773bcc-8eda-4228-92ec-5b09361dd9f1"),
                            FoodDescription = "Appetizer",
                            FoodName = "Fried Mantau",
                            FoodPrice = 22000m
                        },
                        new
                        {
                            Id = new Guid("889964ae-3c02-4b98-8695-8b45d1e5904c"),
                            FoodDescription = "Appetizer",
                            FoodName = "Fried Potato",
                            FoodPrice = 35000m
                        },
                        new
                        {
                            Id = new Guid("02f1a833-c09a-42a5-a459-e5aad275d806"),
                            FoodDescription = "Main Menu",
                            FoodName = "Chicken Crispy",
                            FoodPrice = 75000m
                        });
                });

            modelBuilder.Entity("Resto.API.Model.Domain.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPayment")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = new Guid("6e1305b1-56ae-4e2b-8ed0-6783983b0901"),
                            OrderDate = new DateTime(2023, 9, 15, 7, 30, 48, 214, DateTimeKind.Local).AddTicks(1076),
                            TotalPayment = 298000m
                        });
                });

            modelBuilder.Entity("Resto.API.Model.Domain.OrderDetails", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Resto.API.Model.Domain.Transaction", b =>
                {
                    b.Property<int>("TransId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TransId");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
